name: DAST Scan

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_call:

jobs:
  build-and-start:
    name: Build and Start Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build --if-present
      
      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: .
          retention-days: 1

  owasp-zap:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: build-and-start
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download application
        uses: actions/download-artifact@v3
        with:
          name: app-build
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install and start application
        run: |
          npm install
          npm start > /tmp/app.log 2>&1 &
          sleep 15
          curl -s http://localhost:3000 || echo "Application not responding"
        env:
          NODE_ENV: test
          PORT: 3000
      
      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          artifact_name: 'zap-report'
        continue-on-error: true
      
      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-report
          path: report_html.html
          retention-days: 30
      
      - name: Application logs
        if: always()
        run: cat /tmp/app.log || true

  nuclei-scan:
    name: Nuclei DAST Scan
    runs-on: ubuntu-latest
    needs: build-and-start
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download application
        uses: actions/download-artifact@v3
        with:
          name: app-build
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install and start application
        run: |
          npm install
          npm start > /tmp/app.log 2>&1 &
          sleep 15
          curl -s http://localhost:3000 || echo "Application not responding"
        env:
          NODE_ENV: test
          PORT: 3000
      
      - name: Run Nuclei scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: 'http://localhost:3000'
          flags: '-severity high,critical -json-export nuclei-report.json'
        continue-on-error: true
      
      - name: Upload Nuclei report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nuclei-report
          path: nuclei-report.json
          retention-days: 30
      
      - name: Application logs
        if: always()
        run: cat /tmp/app.log || true
